# netlify.toml

[build]
  # 构建命令：编译我们的 Go 函数
  # -o 指定输出文件路径和名称。Netlify 会在这个目录里寻找可执行文件。
  # 在项目根目录执行，为每个函数目录构建一个 main 可执行文件。
  command = "for dir in netlify/functions/*; do function_name=$(basename $dir); go build -o \"netlify/functions/${function_name}/main\" \"./netlify/functions/${function_name}/\"; done"

# 函数目录
  functions = "netlify/functions/"

[functions]
  # 明确指定 Go 函数的运行时
  # 这有助于 Netlify 优化构建过程
  included_files = ["**/*.go", "go.mod", "go.sum"]

[functions."keep-alive"]
# 调度计划:
# - Cron 表达式: "*/5 1-15 * * *"
# - UTC 时间: 每天的 01:00 到 15:59 之间，每5分钟执行一次。
# - 对应东八区时间 (UTC+8): 每天的 09:00 到 23:59 之间，每5分钟执行一次。
schedule = "*/5 1-15 * * *"